
### sign in api

POST http://localhost:3002/signIn
Content-Type: application/json

{
    "user_id": "6",
    "name": "krish",
    "email":"krish123@gmail.com",
    "password": "krish123"
}

### Log in api

POST http://localhost:3002/login
Content-Type: application/json

{
    "name": "hari",
    "password":"hari123"
}

### change profile details api
PUT http://localhost:3002/updateProfileDetails/?name="hari"
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiJHtuYW1lfSIsImlhdCI6MTczMTQ3MjgxNH0.-yeKiMon-XnPqmAOeIfE6fb0IabwvBTfNxchCrjo9kQ
Content-Type: application/json 

{   
    "newUsername": "hariKrishna",
    "email":"hariKrishna123@gmail.com",
    "password": "hariKrishna123"
}

### get to do list 

GET http://localhost:3002/todo/list/hari

### create a to do and post in the table 

POST http://localhost:3002/newToDo/ram 
Content-Type: application/json

{
    "to_do_id": "9",
    "description": "Learn Java",
    "status": "pending"
}

### deleting a specific to do 

DELETE http://localhost:3002/delete/todo/4
